#! pip install --upgrade google-cloud-aiplatform
from google.cloud import aiplatform
import vertexai.preview
dir(aiplatform)
['Artifact', 'AutoMLForecastingTrainingJob', 'AutoMLImageTrainingJob', 'AutoMLTabularTrainingJob', 'AutoMLTextTrainingJob', 'AutoMLVideoTrainingJob', 'BatchPredictionJob', 'Context', 'CustomContainerTrainingJob', 'CustomJob', 'CustomPythonPackageTrainingJob', 'CustomTrainingJob', 'Endpoint', 'EntityType', 'Execution', 'Experiment', 'ExperimentRun', 'Feature', 'Featurestore', 'HyperparameterTuningJob', 'ImageDataset', 'MatchingEngineIndex', 'MatchingEngineIndexEndpoint', 'Model', 'ModelDeploymentMonitoringJob', 'ModelEvaluation', 'ModelRegistry', 'PipelineJob', 'PipelineJobSchedule', 'PrivateEndpoint', 'SequenceToSequencePlusForecastingTrainingJob', 'TabularDataset', 'TemporalFusionTransformerForecastingTrainingJob', 'Tensorboard', 'TensorboardExperiment', 'TensorboardRun', 'TensorboardTimeSeries', 'TextDataset', 'TimeSeriesDataset', 'TimeSeriesDenseEncoderForecastingTrainingJob', 'VideoDataset', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_pipeline_based_service', '_publisher_models', 'aiplatform_version', 'autolog', 'base', 'compat', 'constants', 'datasets', 'end_run', 'end_upload_tb_log', 'explain', 'featurestore', 'gapic', 'get_experiment_df', 'get_experiment_model', 'get_pipeline_df', 'helpers', 'hyperparameter_tuning', 'init', 'initializer', 'jobs', 'log', 'log_classification_metrics', 'log_metrics', 'log_model', 'log_params', 'log_time_series_metrics', 'matching_engine', 'metadata', 'model_evaluation', 'model_monitoring', 'models', 'pipeline_job_schedules', 'pipeline_jobs', 'preview', 'save_model', 'schedules', 'schema', 'start_execution', 'start_run', 'start_upload_tb_log', 'tensorboard', 'training_jobs', 'upload_tb_log', 'uploader_tracker', 'utils', 'v1', 'v1beta1', 'version']

import vertexai.preview
 dir (vertexai.preview)
['VertexModel', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_workflow', 'developer', 'end_run', 'from_pretrained', 'get_experiment_df', 'global_config', 'hyperparameter_tuning', 'init', 'initializer', 'log_classification_metrics', 'log_metrics', 'log_params', 'log_time_series_metrics', 'metadata', 'model_utils', 'register', 'remote', 'remote_decorator', 'start_run', 'tabular_models']
